using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace jwdiadata.Migrations
{
    /// <inheritdoc />
    public partial class SurveyData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "GeochemSurveyDataModels",
                columns: table => new
                {
                    SampleID = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    GSWANO = table.Column<int>(type: "int", nullable: true),
                    Extraction_Date = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Batch_No = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    QMAPID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DLat = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DLong = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    EASTING = table.Column<int>(type: "int", nullable: true),
                    NORTHING = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RELIABILITY = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SAMPLETYPE = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LITHNAME = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SITENO = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SITEID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ORIGNAME = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Ag_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Al_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ars_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Au_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    B_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ba_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Be_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Bi_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    C_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ca_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cd_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ce_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cl_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Co_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cr_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cs_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cu_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Dy_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Er_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Eu_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    F_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Fe_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ga_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Gd_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ge_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Hf_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Hg_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ho_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ind_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    K_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    La_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    LABnegNR_NONE = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Li_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Lu_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Mg_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Mn_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Mo_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Nb_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Nd_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ni_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    P_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pb_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pr_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Rb_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sb_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sc_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Se_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Si_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sm_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sn_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sr_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ta_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Tb_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Te_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Th_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ti_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Tl_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Tm_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    U_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    V_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    W_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Y_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Yb_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Zn_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Zr_ppm = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Err_143_Nd = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Err_87_Sr = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ppm_sum = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ag_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Al_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ars_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Au_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    B_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ba_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Be_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Bi_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    C_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ca_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cd_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ce_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cl_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Co_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cr_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cs_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cu_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Dy_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Er_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Eu_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    F_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Fe_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ga_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Gd_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ge_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Hf_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Hg_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ho_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ind_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    K_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    La_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Li_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Lu_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Mg_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Mn_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Mo_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Nb_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Nd_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ni_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    P_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pb_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pr_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Rb_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sb_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sc_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Se_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Si_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sm_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sn_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sr_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ta_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Tb_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Te_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Th_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ti_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Tl_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Tm_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    U_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    V_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    W_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Y_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Yb_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Zn_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Zr_ppm_pct = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Top_1_Elements = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Elements_over_10 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    all_present_elements = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GeochemSurveyDataModels", x => x.SampleID);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "GeochemSurveyDataModels");
        }
    }
}
