// <auto-generated />
using System;
using JWDIADATA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace jwdiadata.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250305090506_SurveyData")]
    partial class SurveyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JWDIADATA.Data.Entities.WeatherDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("avghumidity")
                        .HasColumnType("int");

                    b.Property<decimal?>("avgtemp_c")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("avgtemp_f")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("avgvis_km")
                        .HasColumnType("int");

                    b.Property<int?>("avgvis_miles")
                        .HasColumnType("int");

                    b.Property<int?>("condition_code")
                        .HasColumnType("int");

                    b.Property<string>("condition_icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condition_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("daily_chance_of_rain")
                        .HasColumnType("int");

                    b.Property<int?>("daily_chance_of_snow")
                        .HasColumnType("int");

                    b.Property<int?>("daily_will_it_rain")
                        .HasColumnType("int");

                    b.Property<int?>("daily_will_it_snow")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("date_epoch")
                        .HasColumnType("int");

                    b.Property<int?>("hour")
                        .HasColumnType("int");

                    b.Property<decimal?>("maxtemp_c")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("maxtemp_f")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("maxwind_kph")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("maxwind_mph")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("mintemp_c")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("mintemp_f")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("moon_illumination")
                        .HasColumnType("int");

                    b.Property<string>("moon_phase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("moonrise")
                        .HasColumnType("int");

                    b.Property<int?>("moonset")
                        .HasColumnType("int");

                    b.Property<int?>("sunrise")
                        .HasColumnType("int");

                    b.Property<int?>("sunset")
                        .HasColumnType("int");

                    b.Property<decimal?>("totalprecip_in")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("totalprecip_mm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("totalsnow_cm")
                        .HasColumnType("int");

                    b.Property<int?>("uv")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherDataModels");
                });

            modelBuilder.Entity("dataintegrationexample.GeochemSurveyDataModel", b =>
                {
                    b.Property<string>("SampleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Ag_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ag_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Al_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Al_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ars_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ars_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Au_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Au_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("B_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("B_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ba_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ba_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Batch_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Be_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Be_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Bi_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Bi_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("C_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("C_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ca_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ca_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cd_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cd_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ce_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ce_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cl_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cl_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Co_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Co_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cr_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cr_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cs_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cs_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cu_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cu_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DLat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DLong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Dy_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Dy_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EASTING")
                        .HasColumnType("int");

                    b.Property<string>("Elements_over_10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Er_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Er_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Err_143_Nd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Err_87_Sr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Eu_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Eu_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Extraction_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("F_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("F_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Fe_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Fe_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GSWANO")
                        .HasColumnType("int");

                    b.Property<decimal?>("Ga_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ga_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Gd_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Gd_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ge_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ge_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hf_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hf_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hg_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hg_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ho_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ho_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ind_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ind_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("K_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("K_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LABnegNR_NONE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LITHNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("La_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("La_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Li_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Li_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Lu_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Lu_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mg_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mg_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mn_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mn_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mo_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mo_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NORTHING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Nb_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nb_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nd_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nd_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ni_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ni_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ORIGNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("P_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pb_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pb_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pr_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pr_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QMAPID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELIABILITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Rb_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rb_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SAMPLETYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITEID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Sb_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sb_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sc_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sc_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Se_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Se_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Si_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Si_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sm_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sm_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sn_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sn_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sr_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sr_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ta_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ta_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tb_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tb_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Te_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Te_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Th_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Th_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ti_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ti_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tl_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tl_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tm_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tm_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Top_1_Elements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("U_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("U_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("V_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("W_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("W_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Y_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Y_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Yb_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Yb_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Zn_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Zn_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Zr_ppm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Zr_ppm_pct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("all_present_elements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ppm_sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SampleID");

                    b.ToTable("GeochemSurveyDataModels");
                });
#pragma warning restore 612, 618
        }
    }
}
