// <auto-generated />
using System;
using JWDIADATA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace jwdiadata.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JWDIADATA.Data.Entities.WeatherDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("avghumidity")
                        .HasColumnType("int");

                    b.Property<decimal?>("avgtemp_c")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("avgtemp_f")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("avgvis_km")
                        .HasColumnType("int");

                    b.Property<int?>("avgvis_miles")
                        .HasColumnType("int");

                    b.Property<int?>("condition_code")
                        .HasColumnType("int");

                    b.Property<string>("condition_icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condition_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("daily_chance_of_rain")
                        .HasColumnType("int");

                    b.Property<int?>("daily_chance_of_snow")
                        .HasColumnType("int");

                    b.Property<int?>("daily_will_it_rain")
                        .HasColumnType("int");

                    b.Property<int?>("daily_will_it_snow")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("date_epoch")
                        .HasColumnType("int");

                    b.Property<int?>("hour")
                        .HasColumnType("int");

                    b.Property<decimal?>("maxtemp_c")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("maxtemp_f")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("maxwind_kph")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("maxwind_mph")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("mintemp_c")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("mintemp_f")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("moon_illumination")
                        .HasColumnType("int");

                    b.Property<string>("moon_phase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("moonrise")
                        .HasColumnType("int");

                    b.Property<int?>("moonset")
                        .HasColumnType("int");

                    b.Property<int?>("sunrise")
                        .HasColumnType("int");

                    b.Property<int?>("sunset")
                        .HasColumnType("int");

                    b.Property<decimal?>("totalprecip_in")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("totalprecip_mm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("totalsnow_cm")
                        .HasColumnType("int");

                    b.Property<int?>("uv")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherDataModels");
                });
#pragma warning restore 612, 618
        }
    }
}
