using System;

namespace JWDIACONTRACTS.DTO.GeoSurveyDTO;
public class GeochemSurvey
{
    public string? SampleID {get; set;}
    public int? Gswano {get; set;}
    public DateTime? ExtractionDate {get; set;}
    public string? BatchNo {get; set;}
    public string? QmapId {get; set;}
    public decimal? DLat {get; set;}
    public decimal? DLong {get; set;}
    public int? Easting {get; set;}
    public string? Northing {get; set;}
    public string? Reliability {get; set;}
    public string? SampleType {get; set;}
    public string? Lithname {get; set;}
    public string? Sitend {get; set;}
    public string? SiteId {get; set;}
    public string? OrigNme {get; set;}
    public decimal? AgPpm {get; set;}
    public decimal? AlPpm {get; set;}
    public decimal? ArsPpm {get; set;}
    public decimal? AuPpm {get; set;}
    public decimal? BPpm {get; set;}
    public decimal? BaPpm {get; set;}
    public decimal? BePpm {get; set;}
    public decimal? BiPpm {get; set;}
    public decimal? CPpm {get; set;}
    public decimal? CaPpm {get; set;}
    public decimal? CdPpm {get; set;}
    public decimal? CePpm {get; set;}
    public decimal? ClPpm {get; set;}
    public decimal? CoPpm {get; set;}
    public decimal? CrPpm {get; set;}
    public decimal? CsPpm {get; set;}
    public decimal? CuPpm {get; set;}
    public decimal? DyPpm {get; set;}
    public decimal? ErPpm {get; set;}
    public decimal? EuPpm {get; set;}
    public decimal? FPpm {get; set;}
    public decimal? FePpm {get; set;}
    public decimal? GaPpm {get; set;}
    public decimal? GdPpm {get; set;}
    public decimal? GePpm {get; set;}
    public decimal? HfPpm {get; set;}
    public decimal? HgPpm {get; set;}
    public decimal? HoPpm {get; set;}
    public decimal? IndPpm {get; set;}
    public decimal? KPpm {get; set;}
    public decimal? LaPpm {get; set;}
    public decimal? LiPpm {get; set;}
    public decimal? LuPpm {get; set;}
    public decimal? MgPpm {get; set;}
    public decimal? MnPpm {get; set;}
    public decimal? MoPpm {get; set;}
    public decimal? NbPpm {get; set;}
    public decimal? NdPpm {get; set;}
    public decimal? NiPpm {get; set;}
    public decimal? PPpm {get; set;}
    public decimal? PbPpm {get; set;}
    public decimal? PrPpm {get; set;}
    public decimal? RbPpm {get; set;}
    public decimal? SbPpm {get; set;}
    public decimal? ScPpm {get; set;}
    public decimal? SePpm {get; set;}
    public decimal? SiPpm {get; set;}
    public decimal? SmPpm {get; set;}
    public decimal? SnPpm {get; set;}
    public decimal? SrPpm {get; set;}
    public decimal? TaPpm {get; set;}
    public decimal? TbPpm {get; set;}
    public decimal? TePpm {get; set;}
    public decimal? ThPpm {get; set;}
    public decimal? TiPpm {get; set;}
    public decimal? TlPpm {get; set;}
    public decimal? TmPpm {get; set;}
    public decimal? UPpm {get; set;}
    public decimal? VPpm {get; set;}
    public decimal? WPpm {get; set;}
    public decimal? YPpm {get; set;}
    public decimal? YbPpm {get; set;}
    public decimal? ZnPpm {get; set;}
    public decimal? ZrPpm {get; set;}
    public decimal? AgPpmPct {get; set;}
    public decimal? AlPpmPct {get; set;}
    public decimal? ArsPpmPct {get; set;}
    public decimal? AuPpmPct {get; set;}
    public decimal? BPpmPct {get; set;}
    public decimal? BaPpmPct {get; set;}
    public decimal? BePpmPct {get; set;}
    public decimal? BiPpmPct {get; set;}
    public decimal? CPpmPct {get; set;}
    public decimal? CaPpmPct {get; set;}
    public decimal? CdPpmPct {get; set;}
    public decimal? CePpmPct {get; set;}
    public decimal? ClPpmPct {get; set;}
    public decimal? CoPpmPct {get; set;}
    public decimal? CrPpmPct {get; set;}
    public decimal? CsPpmPct {get; set;}
    public decimal? CuPpmPct {get; set;}
    public decimal? DyPpmPct {get; set;}
    public decimal? ErPpmPct {get; set;}
    public decimal? EuPpmPct {get; set;}
    public decimal? FPpmPct {get; set;}
    public decimal? FePpmPct {get; set;}
    public decimal? GaPpmPct {get; set;}
    public decimal? GdPpmPct {get; set;}
    public decimal? GePpmPct {get; set;}
    public decimal? HfPpmPct {get; set;}
    public decimal? HgPpmPct {get; set;}
    public decimal? HoPpmPct {get; set;}
    public decimal? IndPpmPct {get; set;}
    public decimal? KPpmPct {get; set;}
    public decimal? LaPpmPct {get; set;}
    public decimal? LiPpmPct {get; set;}
    public decimal? LuPpmPct {get; set;}
    public decimal? MgPpmPct {get; set;}
    public decimal? MnPpmPct {get; set;}
    public decimal? MoPpmPct {get; set;}
    public decimal? NbPpmPct {get; set;}
    public decimal? NdPpmPct {get; set;}
    public decimal? NiPpmPct {get; set;}
    public decimal? PPpmPct {get; set;}
    public decimal? PbPpmPct {get; set;}
    public decimal? PrPpmPct {get; set;}
    public decimal? RbPpmPct {get; set;}
    public decimal? SbPpmPct {get; set;}
    public decimal? ScPpmPct {get; set;}
    public decimal? SePpmPct {get; set;}
    public decimal? SiPpmPct {get; set;}
    public decimal? SmPpmPct {get; set;}
    public decimal? SnPpmPct {get; set;}
    public decimal? SrPpmPct {get; set;}
    public decimal? TaPpmPct {get; set;}
    public decimal? TbPpmPct {get; set;}
    public decimal? TePpmPct {get; set;}
    public decimal? ThPpmPct {get; set;}
    public decimal? TiPpmPct {get; set;}
    public decimal? TlPpmPct {get; set;}
    public decimal? TmPpmPct {get; set;}
    public decimal? UPpmPct {get; set;}
    public decimal? VPpmPct {get; set;}
    public decimal? WPpmPct {get; set;}
    public decimal? YPpmPct {get; set;}
    public decimal? YbPpmPct {get; set;}
    public decimal? ZnPpmPct {get; set;}
    public decimal? ZrPpmPct {get; set;}
    public string? TopElement {get; set;}
    public string? ElementsOver10 {get; set;}
    public string? allPresentElements {get; set;}

    
}
